# Generated by Django 2.2.2 on 2019-06-16 09:31

from django.db import migrations, models
import viewer.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(default='file', max_length=50)),
                ('file_data', models.FileField(upload_to='', validators=[viewer.validators.validate_type_excel])),
            ],
        ),
    ]
